local FWR = FarmWiseReforged or {}
FarmWiseReforged = FWR

FWR.UI_CONFIG = FWR.UI_CONFIG or {}

FWR.UI_CONFIG.MainFrame = {
    frame = {
        name = "FarmWiseReforgedMainFrame",
        width = 405,
        scale = 1.0,
        movable = true,
        clampToScreen = true,
        strata = "MEDIUM",
        anchor = {
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 40,
            y = 120,
        },
        backdrop = {
            bgColor = { 0.05, 0.05, 0.06 },
            bgAlpha = 0.94,
            borderColor = { 0.72, 0.62, 0.33 },
            borderAlpha = 0.95,
            edgeSize = 12,
            insets = { left = 3, right = 3, top = 3, bottom = 3 },
        },
    },



    scroll = {
        x = 13,
        y = 2,
        width = 0,
        height = 10,
    },

    blocks = {
        header = {
            x = 0,
            y = 0,
            height = 45,
            bgColor = { 0.11, 0.11, 0.12 },
            bgAlpha = 0.90,
        },
        content = {
            insetLeft = 0,
            insetRight = 0,
            insetTop = 0,
            insetBottom = 0,
            height = 148,
            bgColor = { 0.02, 0.02, 0.02 },
            bgAlpha = 1.0,
        },
        footer = {
            x = 0,
            y = 0,
            height = 30,
            bgColor = { 0.11, 0.11, 0.12 },
            bgAlpha = 0.90,
        },
    },

    elements = {
        title = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 5,
            y = 4,
            font = "GameFontNormalLarge",
            text = "FarmWise",
            textColor = { 1.0, 0.82, 0.0 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        titleAccent = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 1,
            spacingFromTitle = 5,
            font = "GameFontNormalLarge",
            fontPath = "Fonts\\MORPHEUS.ttf",
            fontSize = 17,
            fontFlags = "OUTLINE",
            text = "Reforge",
            textColor = { 1.0, 0.42, 0.0 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        zone = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 5,
            y = 21,
            font = "GameFontHighlightSmall",
            text = "Zone Placeholder",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        zoneSeparator = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 21,
            spacingFromZone = 6,
            text = "-",
            font = "GameFontHighlightSmall",
            textColor = { 0.75, 0.75, 0.78 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        subzone = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 21,
            spacingFromSeparator = 6,
            font = "GameFontHighlightSmall",
            text = "Subzone Placeholder",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        totalTimeLabel = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 5,
            y = 33,
            font = "GameFontHighlightSmall",
            text = "Total:",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        totalTimeValue = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 40,
            y = 33,
            spacingFromLabel = 0,
            font = "GameFontHighlightSmall",
            text = "00:00",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        runtimeSeparator = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 33,
            spacingFromTotalValue = 8,
            text = "-",
            font = "GameFontHighlightSmall",
            textColor = { 0.75, 0.75, 0.78 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        runtimeLabel = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 33,
            spacingFromSeparator = 8,
            font = "GameFontHighlightSmall",
            text = "Session:",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        runtimeValue = {
            parentBlock = "header",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 33,
            spacingFromLabel = 4,
            font = "GameFontHighlightSmall",
            text = "00:00",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        timeDisplayFormat = {
            showHoursWhenZero = false,
            zeroPadHours = false,
            zeroPadMinutes = true,
            zeroPadSeconds = true,
            timeSeparator = ":",
        },
        idle = {
            parentBlock = "header",
            point = "TOPRIGHT",
            relativePoint = "TOPRIGHT",
            x = -10,
            y = 5,
            font = "GameFontNormal",
            text = "IDLE",
            textColor = { 1.0, 0.15, 0.15 },
            textAlpha = 1.0,
            justifyH = "RIGHT",
            justifyV = "TOP",
        },
        scanner = {
            parentBlock = "header",
            point = "TOPRIGHT",
            relativePoint = "TOPRIGHT",
            x = -10,
            y = 33,
            font = "GameFontHighlightSmall",
            text = "AH prices: not scanned yet",
            textColor = { 0.72, 0.72, 0.74 },
            textAlpha = 1.0,
            justifyH = "RIGHT",
            justifyV = "MIDDLE",
        },
        totalGoldLabel = {
            parentBlock = "footer",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 10,
            y = 2,
            font = "GameFontHighlightSmall",
            text = "Total:",
            textColor = { 1.0, 0.82, 0.0 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
            tooltipText = "Total Gold\nGold looted in what the window currently shows.",
            hitboxWidth = 220,
            hitboxHeight = 14,
        },
        totalGoldValue = {
            parentBlock = "footer",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 45,
            y = 2,
            spacingFromLabel = 0,
            font = "GameFontHighlightSmall",
            text = "0|TInterface\\MoneyFrame\\UI-CopperIcon:12:12:2:0|t",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        estimatedGoldPerHourLabel = {
            parentBlock = "footer",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 10,
            y = 15,
            font = "GameFontHighlightSmall",
            text = "EGPH:",
            textColor = { 1.0, 0.82, 0.0 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
            tooltipText = "Estimated Gold Per Hour\nLooted gold divided by the tracked time of what the window currently shows.",
            hitboxWidth = 220,
            hitboxHeight = 14,
        },
        estimatedGoldPerHourValue = {
            parentBlock = "footer",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 45,
            y = 15,
            spacingFromLabel = 0,
            font = "GameFontHighlightSmall",
            text = "0|TInterface\\MoneyFrame\\UI-CopperIcon:12:12:2:0|t",
            textColor = { 0.90, 0.90, 0.92 },
            textAlpha = 1.0,
            justifyH = "LEFT",
            justifyV = "MIDDLE",
        },
        totalGoldMoneyLayout = {
            goldWidthPadding = 6,
            silverWidthPadding = 6,
            copperWidthPadding = 6,
            silverOffsetX = -4,
            silverOffsetY = 0,
            copperOffsetX = -4,
            copperOffsetY = 0,
        },
        estimatedGoldPerHourMoneyLayout = {
            goldWidthPadding = 6,
            silverWidthPadding = 6,
            copperWidthPadding = 6,
            silverOffsetX = -4,
            silverOffsetY = 0,
            copperOffsetX = -4,
            copperOffsetY = 0,
        },
        resetButton = {
            parentBlock = "footer",
            point = "TOPRIGHT",
            relativePoint = "TOPRIGHT",
            x = -145,
            y = 4,
            width = 60,
            height = 20,
            text = "Reset",
        },
        optionsButton = {
            parentBlock = "footer",
            point = "TOPRIGHT",
            relativePoint = "TOPRIGHT",
            x = -80,
            y = 4,
            width = 60,
            height = 20,
            text = "Options",
        },
        advisorButton = {
            parentBlock = "footer",
            point = "TOPRIGHT",
            relativePoint = "TOPRIGHT",
            x = -15,
            y = 4,
            width = 60,
            height = 20,
            text = "Advisor",
        },
    },
}
