local FWR = FarmWiseReforged or {}
FarmWiseReforged = FWR

FWR.UI_CONFIG = FWR.UI_CONFIG or {}

FWR.UI_CONFIG.Rendering = {
    layout = {
        visibleRows = 5,
        rowHeight = 16,
        topPadding = 2,
        bottomPadding = 4,
    },
    columns = {
        gap = 1,
        item = {
            label = "Item Name",
            width = 125,
            visible = true,
            headerAlign = "LEFT",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        quality = {
            label = "",
            width = 15,
            minWidth = 15,
            autoWidth = true,
            visible = true,
            headerAlign = "CENTER",
            dataAlign = "CENTER",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        quantity = {
            label = "Session",
            width = 50,
            minWidth = 50,
            autoWidth = true,
            visible = true,
            headerAlign = "CENTER",
            dataAlign = "RIGHT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        total = {
            label = "Total",
            width = 50,
            minWidth = 50,
            autoWidth = true,
            visible = true,
            headerAlign = "CENTER",
            dataAlign = "RIGHT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        itemPerHour = {
            label = "Item/h",
            width = 50,
            minWidth = 50,
            autoWidth = true,
            visible = true,
            headerAlign = "CENTER",
            dataAlign = "RIGHT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        itemType = {
            label = "Reagent Type",
            width = 85,
            visible = false,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        classification = {
            label = "Profession",
            width = 80,
            visible = false,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        activity = {
            label = "Activity",
            width = 65,
            visible = true,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        expansion = {
            label = "Expansion",
            width = 70,
            visible = false,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        zone = {
            label = "Zone",
            width = 110,
            visible = false,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        subZone = {
            label = "Sub-Zone",
            width = 110,
            visible = false,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
        character = {
            label = "Character",
            width = 110,
            visible = false,
            headerAlign = "CENTER",
            dataAlign = "LEFT",
            dataInsetLeft = 5,
            dataInsetRight = 5,
        },
    },
}
